openapi: 3.1.0
info:
    title: The Back-end API server for The WNI
    version: 0.0.1

servers:
    - url: http://localhost:4000

paths:
    /healthz:
        get:
            summary: Checks if the server is up and active
    /chat:
        $ref: "./chat.yaml"
